### ISSUE TITLE
Testing new releases of Alma

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#638]
To facilitate testing, each release of Alma is released to the sandbox environment before it is released to production. Can we run the marc_liberation test suite against the sandbox, or otherwise use it to test compatibility with new releases?

**Comment by kelynch** [comment]
One way we could do this: define config parameters in `config/initializers/voyager_helpers.rb` to read from a config YML file and parse based on Rails environment.  Pseudocode example below (modeled on [Figgy](https://github.com/pulibrary/figgy/blob/38696f75fe6cd97b3307daa21edf61f6bb0236fe/config/initializers/figgy.rb)):

## `config/alma_helpers.yml`
```
development:
  db_user: ENV['USER_DEV']
  db_password: ENV['PASS_DEV']
  db_name: ENV['DB_DEV']
test:
  db_user: ENV['USER_TEST']
  db_password: ENV['PASS_TEST']
  db_name: ENV['DB_TEST']
# ...
```

## `config/initializers/alma_helpers.rb`
```
module AlmaHelpers
  def config
    @config ||= config_yaml.with_indifferent_access
  end

  private

  def config_yaml
    config_file = Rails.root.join('config', 'alma_helpers.yml')
    fail "Missing configuration file at: #{config_file}." unless File.exist?(config_file)
    YAML.load(ERB.new(File.read(config_file)).result)[Rails.env]
  end

  module_function :config, :config_yaml
end
```
